### ISSUE TITLE
DRONE_SECRET and Signature Check

### ISSUE THREAD

**Issue by davideperozzi** [spritsail/drone-notify#9]
Hey, good job on the service! Exactly what I needed, thanks for your work!

Is it possible to add a signature validation via `DRONE_SECRET`?
 
If I would expose the service right now (which I need to do in my case), anyone from outside could "POST" to it. 
I have done it in JS a while back for a drone webhook plugin for slack. If you want I can share the functions with you in order to check if the request is signed properly or maybe there's a library in python for that already.

I can also  implement it in your current setup. If you're open to it, let me know :)

**Comment by frebib** [comment]
This is definitely something we should do; a welcome improvement! I'd be happy to accept a PR for this if you'd like to implement it, or I can give it a go myself.

I found the docs on how Drone expects this to be handled. https://docs.drone.io/webhooks/overview/#authorization
There is this library https://pypi.org/project/requests-http-signature/ although it could be tricky to use it as the new code uses aiohttp instead of requests (although if there is a way to use requests in an asyncio context we can switch to use that).

Fair warning that I'm midway through a big refactor of this code, but it shouldn't be too hard to adapt any pull requests.

**Comment by davideperozzi** [comment]
@frebib I added the verification only, more is probably not necessary. You can check the PR here: https://github.com/spritsail/drone-notify/pull/10. I didn't use a library since the signature verification we need for drone is "trivial" and consists of just 4 functions. As I said in the PR, not very good with python, you might want to check and test all of it properly. Let me know if there are any issues - happy to help! :)
